"project_identifier": "flash"
"base_path": "/app/src/main/res"

"files": [
  {
    "source" : "/values/strings.xml",
    "translation" : "/values-%android_code%/%original_file_name%"
  },
  {
    "source" : "/values/strings_*.xml",
    "translation" : "/values-%android_code%/%original_file_name%",
    "ignore" : [
      "/values/strings_no_translate.xml"
    ]
  }
]